# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('saas_core', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('in_progress', 'Em Execução / Lavagem'), ('completed', 'Pronto / Finalizado'), ('delivered', 'Entregue ao Cliente'), ('cancelled', 'Cancelado')], default='waiting', max_length=20, verbose_name='Status no Pátio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Bruto (R$)')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto (R$)')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Final (R$)')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro em Espécie'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('monthly_invoice', 'Faturamento Mensal (Frota)'), ('pending', 'Pendente de Pagamento')], default='pending', max_length=30, verbose_name='Forma de Pagamento')),
                ('billing_status', models.CharField(choices=[('NOT_APPLICABLE', 'Não Aplicável (Avulso)'), ('PENDING', 'Pendente de Fatura'), ('INVOICED', 'Faturado em Lote'), ('PAID', 'Fatura Paga')], default='NOT_APPLICABLE', max_length=20, verbose_name='Status de Faturamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações / Instruções Especiais')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início do Atendimento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão do Serviço')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entrega do Veículo')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Lavador / Responsável')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Cliente')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.servicetype', verbose_name='Serviço Solicitado')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('stage', models.CharField(choices=[('before', 'Antes (Entrada)'), ('after', 'Depois (Conclusão)'), ('damage', 'Avaria Prévia')], default='before', max_length=20, verbose_name='Etapa da Foto')),
                ('image', models.ImageField(upload_to='order_inspections/', verbose_name='Imagem da Vistoria')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda / Observação')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Foto da Vistoria',
                'verbose_name_plural': 'Fotos da Vistoria',
                'ordering': ['stage', 'created_at'],
            },
        ),
    ]
