# Generated by Django 5.2.17 on 2026-09-06 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_vehicle_plate_and_more'),
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando'), ('in_progress', 'Em Atendimento'), ('washing', 'Em Atendimento'), ('completed', 'Pronto / Finalizado'), ('delivered', 'Entregue ao Cliente'), ('cancelled', 'Cancelado')], default='waiting', max_length=20, verbose_name='Status no Pátio'),
        ),
        migrations.AddIndex(
            model_name='orderphoto',
            index=models.Index(fields=['order', 'stage'], name='orders_orde_order_i_d31d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['company', 'status', '-created_at'], name='orders_serv_company_5d8a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['company', 'delivered_at'], name='orders_serv_company_f99b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['customer', 'status'], name='orders_serv_custome_62fc01_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['company', 'billing_status'], name='orders_serv_company_3be9a5_idx'),
        ),
    ]
