# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Cliente / Razão Social')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CPF / CNPJ')),
                ('billing_type', models.CharField(choices=[('per_service', 'Avulso (Pagamento por Serviço)'), ('monthly', 'Faturamento Mensal / Frota')], default='per_service', max_length=20, verbose_name='Tipo de Faturamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário App Mobile')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca / Fabricante')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('vehicle_type', models.CharField(choices=[('hatch', 'Hatch'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Picape'), ('moto', 'Motocicleta'), ('van', 'Van / Utilitário'), ('truck', 'Caminhão')], default='sedan', max_length=20, verbose_name='Porte / Tipo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto do Veículo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['brand', 'model'],
                'unique_together': {('company', 'plate')},
            },
        ),
    ]
