# Generated by Django 5.2.17 on 2026-09-06 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Placa'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'name'], name='customers_c_company_10527e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'phone'], name='customers_c_company_e97128_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'user'], name='customers_c_company_051679_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'plate'], name='customers_v_company_d860b9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['customer'], name='customers_v_custome_beb603_idx'),
        ),
    ]
