# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Comissão (R$)')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Pagamento'), ('paid', 'Pago ao Funcionário')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário / Lavador')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.serviceorder', verbose_name='Ordem de Serviço (Origem)')),
            ],
            options={
                'verbose_name': 'Comissão de Funcionário',
                'verbose_name_plural': 'Comissões de Funcionários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('calc_type', models.CharField(choices=[('percentage', 'Porcentagem (%)'), ('fixed', 'Valor Fixo (R$)')], default='percentage', max_length=20, verbose_name='Tipo de Cálculo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor ou Percentual')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='services.servicetype', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Regra de Comissão',
                'verbose_name_plural': 'Regras de Comissão',
                'unique_together': {('company', 'service_type')},
            },
        ),
    ]
