# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('reference_month', models.PositiveSmallIntegerField(verbose_name='Mês de Referência (1-12)')),
                ('reference_year', models.PositiveSmallIntegerField(verbose_name='Ano de Referência')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total Consolidado (R$)')),
                ('status', models.CharField(choices=[('open', 'Aberta / Aguardando Pagamento'), ('paid', 'Liquidada / Paga'), ('cancelled', 'Cancelada')], default='open', max_length=20, verbose_name='Status da Fatura')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Liquidação')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_invoices', to='customers.customer', verbose_name='Cliente Frotista')),
            ],
            options={
                'verbose_name': 'Fatura Mensal',
                'verbose_name_plural': 'Faturas Mensais',
                'ordering': ['-reference_year', '-reference_month'],
                'unique_together': {('company', 'customer', 'reference_month', 'reference_year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('vehicle_plate', models.CharField(max_length=15, verbose_name='Placa do Veículo')),
                ('service_name', models.CharField(max_length=150, verbose_name='Serviço Executado')),
                ('service_date', models.DateTimeField(verbose_name='Data do Atendimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado (R$)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.monthlyinvoice', verbose_name='Fatura')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='orders.serviceorder', verbose_name='Ordem de Serviço (Origem)')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
                'ordering': ['service_date'],
            },
        ),
    ]
