# Generated by Django 5.2.17 on 2026-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyinvoice',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('paid', 'Liquidada'), ('cancelled', 'Cancelada')], default='open', max_length=20, verbose_name='Status da Fatura'),
        ),
    ]
