# Generated by Django 5.2.17 on 2026-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['company', 'is_active'], name='services_se_company_b2aeca_idx'),
        ),
    ]
