# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('category_type', models.CharField(choices=[('income', 'Receita / Entrada'), ('expense', 'Despesa / Saída')], default='income', max_length=20, verbose_name='Tipo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria do Caixa',
                'verbose_name_plural': 'Categorias do Caixa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do Lançamento')),
                ('entry_type', models.CharField(choices=[('income', 'Receita / Entrada'), ('expense', 'Despesa / Saída')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro em Espécie'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('bank_transfer', 'Transferência Bancária'), ('monthly_invoice', 'Faturamento Mensal / Boleto'), ('other', 'Outro')], default='pix', max_length=30, verbose_name='Forma de Pagamento')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Lançamento')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.cashcategory', verbose_name='Categoria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='orders.serviceorder', verbose_name='Ordem de Serviço (Origem)')),
            ],
            options={
                'verbose_name': 'Lançamento de Caixa',
                'verbose_name_plural': 'Livro Caixa',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
