# Generated by Django 5.2.17 on 2026-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['company', '-entry_date'], name='finance_cas_company_7bcd8c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['company', 'entry_type', '-entry_date'], name='finance_cas_company_c28b5b_idx'),
        ),
    ]
