# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='Saldo de Pontos')),
                ('total_points_earned', models.PositiveIntegerField(default=0, verbose_name='Total Acumulado na História')),
                ('total_rewards_redeemed', models.PositiveIntegerField(default=0, verbose_name='Recompensas Resgatadas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Conta de Fidelidade',
                'verbose_name_plural': 'Contas de Fidelidade',
                'unique_together': {('company', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(choices=[('earned', 'Pontos Ganhos'), ('redeemed', 'Recompensa Resgatada'), ('reversed', 'Estorno de Pontos')], max_length=20, verbose_name='Tipo de Evento')),
                ('points', models.IntegerField(verbose_name='Quantidade de Pontos (+/-)')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição / Motivo')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='loyalty.loyaltyaccount', verbose_name='Conta de Fidelidade')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_events', to='orders.serviceorder', verbose_name='Ordem de Serviço (Origem)')),
            ],
            options={
                'verbose_name': 'Evento de Fidelidade',
                'verbose_name_plural': 'Extrato de Fidelidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(default='Clube Fidelidade', max_length=100, verbose_name='Nome do Programa')),
                ('points_needed_for_reward', models.PositiveIntegerField(default=100, verbose_name='Pontos para Resgate')),
                ('reward_description', models.CharField(default='Lavagem Completa Grátis', max_length=255, verbose_name='Descrição da Recompensa')),
                ('points_per_service', models.PositiveIntegerField(default=10, verbose_name='Pontos Base por Serviço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Programa Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Programa de Fidelidade',
                'verbose_name_plural': 'Programas de Fidelidade',
            },
        ),
    ]
