# Generated by Django 5.2.17 on 2026-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_loyaltyprogram_reward_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='points_per_service',
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='reward_product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Produto / Prêmio'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='reward_type',
            field=models.CharField(choices=[('service', 'Serviço do Lava-Jato'), ('product', 'Produto / Brinde Personalizado')], default='service', max_length=20, verbose_name='Tipo de Recompensa'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points_needed_for_reward',
            field=models.PositiveIntegerField(default=100, verbose_name='Alvo de Pontos para Resgate'),
        ),
    ]
