# Generated by Django 5.2.17 on 2026-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_vehicle_plate_and_more'),
        ('loyalty', '0003_remove_loyaltyprogram_points_per_service_and_more'),
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['company', 'customer'], name='loyalty_loy_company_77ddc6_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyevent',
            index=models.Index(fields=['account', '-created_at'], name='loyalty_loy_account_d52159_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyevent',
            index=models.Index(fields=['company', '-created_at'], name='loyalty_loy_company_a5e4f4_idx'),
        ),
    ]
