# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('code', models.CharField(choices=[('basic', 'Básico (Start)'), ('pro', 'Profissional (Pro)'), ('premium', 'Premium (Master)')], max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mensal (R$)')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name='Limite de Usuários/Operadores')),
                ('has_mobile_booking', models.BooleanField(default=True, verbose_name='Agendamento pelo App')),
                ('has_loyalty', models.BooleanField(default=False, verbose_name='Programa de Fidelidade Digital')),
                ('has_monthly_billing', models.BooleanField(default=False, verbose_name='Faturamento Mensal p/ Frotas')),
                ('has_inspections', models.BooleanField(default=False, verbose_name='Vistoria com Fotos Antes/Depois')),
                ('has_commissions', models.BooleanField(default=False, verbose_name='Comissões de Funcionários')),
                ('has_push_notifications', models.BooleanField(default=False, verbose_name='Notificações Push no App')),
                ('has_custom_reports', models.BooleanField(default=False, verbose_name='Relatórios Gerenciais Avançados (DRE)')),
            ],
            options={
                'verbose_name': 'Plano SaaS',
                'verbose_name_plural': 'Planos SaaS',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='Razão Social / Nome Fantasia')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador URL (Slug)')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CNPJ / CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Principal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone / WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logotipo')),
                ('status', models.CharField(choices=[('trial', 'Período de Testes'), ('active', 'Ativo'), ('past_due', 'Em Atraso'), ('blocked', 'Bloqueado'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Status da Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='saas_core.plan', verbose_name='Plano Contratado')),
            ],
            options={
                'verbose_name': 'Empresa (Tenant)',
                'verbose_name_plural': 'Empresas (Tenants)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='saas_core.company', verbose_name='Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='saas_core.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura SaaS',
                'verbose_name_plural': 'Assinaturas SaaS',
                'ordering': ['-due_date'],
            },
        ),
    ]
