# Generated by Django 5.2.17 on 2026-09-04 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Ajudante')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / WhatsApp')),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações / Especialidade')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Ajudante Diário (Diarista)',
                'verbose_name_plural': 'Ajudantes Diários (Diaristas)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('work_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Trabalho')),
                ('shift', models.CharField(choices=[('full_day', 'Dia Completo'), ('half_day', 'Meio Período'), ('night', 'Turno Noturno / Extra')], default='full_day', max_length=20, verbose_name='Turno / Período')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Diária (R$)')),
                ('activity_description', models.CharField(blank=True, default='Lavagem e secagem geral', max_length=200, verbose_name='Função / Atividade Realizada')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Pagamento'), ('paid', 'Pago ao Ajudante')], default='pending', max_length=20, verbose_name='Status do Pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Baixa / Pagamento')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro em Espécie'), ('bank_transfer', 'Transferência Bancária'), ('other', 'Outro')], default='pix', max_length=30, verbose_name='Forma de Pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cash_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_works', to='finance.cashentry', verbose_name='Lançamento no Livro Caixa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='employees.dailyhelper', verbose_name='Ajudante Diário')),
            ],
            options={
                'verbose_name': 'Diária de Ajudante',
                'verbose_name_plural': 'Diárias de Ajudantes',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('role_title', models.CharField(default='Lavador / Detalhador', max_length=100, verbose_name='Cargo / Função')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / WhatsApp')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Mensal Fixo (R$)')),
                ('payment_day', models.PositiveSmallIntegerField(default=5, help_text='Dia do mês para pagamento (ex: 5)', verbose_name='Dia do Pagamento')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Admissão / Contratação')),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX para Pagamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Funcionário Ativo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Funcionário Registrado',
                'verbose_name_plural': 'Funcionários Registrados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('reference_month', models.CharField(help_text='Ex: 03/2026', max_length=10, verbose_name='Mês de Referência')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base (R$)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bônus / Adicionais (R$)')),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descontos / Adiantamentos (R$)')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Pago (R$)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro em Espécie'), ('bank_transfer', 'Transferência Bancária'), ('other', 'Outro')], default='pix', max_length=30, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendente')], default='paid', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cash_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='finance.cashentry', verbose_name='Lançamento no Livro Caixa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='employees.registeredemployee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Pagamento de Salário',
                'verbose_name_plural': 'Pagamentos de Salários',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
