# Generated by Django 5.2.17 on 2026-09-03 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('scheduled_date', models.DateField(verbose_name='Data Agendada')),
                ('scheduled_time', models.TimeField(verbose_name='Horário Agendado')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Confirmação'), ('confirmed', 'Confirmado'), ('arrived', 'Veículo no Pátio (OS Criada)'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status do Agendamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='saas_core.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customer', verbose_name='Cliente')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='orders.serviceorder', verbose_name='Ordem de Serviço Gerada')),
                ('preferred_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Operador Preferencial')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.servicetype', verbose_name='Serviço Desejado')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
