# Generated by Django 5.2.17 on 2026-09-06 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('saas_core', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['company', 'scheduled_date', 'scheduled_time'], name='appointment_company_09b753_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['company', 'status'], name='appointment_company_597fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'status'], name='appointment_custome_6b9467_idx'),
        ),
    ]
